sources = Split("""
	main.c
	client.c
	list.c
	keyboard.c
""")

env = Environment(CCFLAGS = ["-Wall", "-std=c99", "-g"])

env.Program(target = "kasswm", source = sources, LIBS = ["xcb", "xcb-keysyms"])
